import { z } from 'zod';
import { FulfillmentType, InventoryMode, ProductStatus } from '@cc/types';
import { moneySchema, nullableUrlSchema, slugSchema } from './common';

export const productOptionValueInputSchema = z.object({
  /** Present when editing an existing value; omitted for new ones. */
  id: z.string().optional(),
  value: z.string().trim().min(1, 'Required').max(60),
  group: z.string().trim().max(60).nullish(),
});

export const productOptionInputSchema = z.object({
  id: z.string().optional(),
  name: z.string().trim().min(1, 'Required').max(40),
  values: z.array(productOptionValueInputSchema).min(1, 'Add at least one value').max(80),
});
export type ProductOptionInput = z.infer<typeof productOptionInputSchema>;

export const productVariantInputSchema = z.object({
  id: z.string().optional(),
  /** Option values by name, in option order: ["iPhone 17 Pro", "Pink", "MagSafe"]. */
  optionValues: z.array(z.string().trim().min(1)).max(4),
  sku: z.string().trim().max(64).nullish(),
  price: moneySchema,
  compareAtPrice: moneySchema.nullish(),
  cost: moneySchema.nullish(),
  stock: z.number().int().min(0).max(1_000_000).default(0),
  enabled: z.boolean().default(true),
  imageUrl: nullableUrlSchema,
  supplierSku: z.string().trim().max(120).nullish(),
});
export type ProductVariantInput = z.infer<typeof productVariantInputSchema>;

export const productMediaInputSchema = z.object({
  id: z.string().optional(),
  url: z.string().trim().min(1),
  alt: z.string().trim().max(160).nullish(),
});

const productBaseSchema = z.object({
  title: z.string().trim().min(2, 'At least 2 characters').max(140),
  slug: slugSchema.optional(),
  description: z.string().trim().max(20_000).nullish(),
  status: z.nativeEnum(ProductStatus).default(ProductStatus.DRAFT),
  category: z.string().trim().max(60).nullish(),
  price: moneySchema,
  compareAtPrice: moneySchema.nullish(),
  cost: moneySchema.nullish(),
  inventoryMode: z.nativeEnum(InventoryMode).default(InventoryMode.NOT_TRACKED),
  fulfillmentType: z.nativeEnum(FulfillmentType).default(FulfillmentType.MANUAL),
  seoTitle: z.string().trim().max(70).nullish(),
  seoDescription: z.string().trim().max(160).nullish(),
  metadata: z.record(z.unknown()).default({}),
  media: z.array(productMediaInputSchema).max(20).default([]),
  options: z.array(productOptionInputSchema).max(4).default([]),
  variants: z.array(productVariantInputSchema).max(500).default([]),
  collectionIds: z.array(z.string()).max(50).default([]),
});

/**
 * A product with options must expose at least one variant, and every variant
 * must carry exactly one value per option. Products with no options get a single
 * implicit "Default" variant generated by the service layer.
 */
function validateVariantShape(
  data: { options: ProductOptionInput[]; variants: ProductVariantInput[] },
  ctx: z.RefinementCtx,
): void {
  if (data.options.length === 0) return;
  if (data.variants.length === 0) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['variants'],
      message: 'Generate variants before saving',
    });
    return;
  }
  data.variants.forEach((variant, index) => {
    if (variant.optionValues.length !== data.options.length) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['variants', index, 'optionValues'],
        message: `Expected ${data.options.length} option value(s)`,
      });
    }
  });
}

export const createProductSchema = productBaseSchema.superRefine(validateVariantShape);
export type CreateProductInput = z.infer<typeof createProductSchema>;

export const updateProductSchema = productBaseSchema.partial().superRefine((data, ctx) => {
  if (data.options === undefined && data.variants === undefined) return;
  validateVariantShape({ options: data.options ?? [], variants: data.variants ?? [] }, ctx);
});
export type UpdateProductInput = z.infer<typeof updateProductSchema>;

export const productListQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  perPage: z.coerce.number().int().min(1).max(100).default(20),
  search: z.string().trim().max(120).optional(),
  status: z.nativeEnum(ProductStatus).optional(),
  collectionId: z.string().optional(),
  sort: z.enum(['newest', 'oldest', 'title', 'priceAsc', 'priceDesc']).default('newest'),
});
export type ProductListQuery = z.infer<typeof productListQuerySchema>;
